---
development:
  cloud_name: indoexchanger
  api_key: '181782398221198'
  api_secret: j_k5DSITkps4R_crovzYAAIWSd0
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: indoexchanger
  api_key: '181782398221198'
  api_secret: j_k5DSITkps4R_crovzYAAIWSd0
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: indoexchanger
  api_key: '181782398221198'
  api_secret: j_k5DSITkps4R_crovzYAAIWSd0
  enhance_image_tag: true
  static_image_support: false
