# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6410c4814efca5c8de2e66a2b8b16a84650cc60a5d0400b308277c6b112469c5a5a40fc35d21123f46d15b1ad845a028015d06d3c99cc3fbcf8db25ac6bfcc67
  mailchimp_api_key: 3897dcba829a449d027bb0cd1cd8fa6f-us15 

test:
  secret_key_base: 42b37e41206d43b57cb48a1a535411fdc63c542ef42fb98ec503590feb0b49ee3f22ed9a71ade2ffff516a36b329b3b40f338daf675c92b79b37b3ef491f9e7c
  mailchimp_api_key: 3897dcba829a449d027bb0cd1cd8fa6f-us15
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE_PROD"] %>
  mailchimp_api_key: 3897dcba829a449d027bb0cd1cd8fa6f-us15

staging: 
  secret_key_base: <%= ENV["SECRET_KEY_BASE_STAG"] %>
  mailchimp_api_key: 3897dcba829a449d027bb0cd1cd8fa6f-us15
